# Raw sequencing data parent directory containing one folder per flow cell, set if using .fast5 as input
storage_data_raw : data

# How to parse the folders found in 'storage_data_raw'. A 'reads' subfolder is
# expected containing the batches of fast5 raw reads.
# A runname pattern could be 20180101_FAH12345_FLO-MIN106_SQK-LSK109_WA01
# Field IDs are zero based.
storage_runname:
    delimiter: '_'
    field_ID: 1
    field_flowcell: 2
    field_kit: 3


# threads per processing batch, if given enough threads with -j n multiple
# batches run in parallel. Also used as resource for cluster jobs.
# Alignments need to be run with at least -j 2 for alignment and sam to bam
# conversion.
threads_basecalling: 4
threads_alignment: 3
threads_samtools : 1
threads_demux: 4


# basecalling
do_basecalling: False                # set to True if basecalling needs to be run and data is provided as .fast5 files. Set to False if data has already been basecalled and is in the sequences folder
# config file for guppy basecalling
basecalling_guppy_config: 'dna_r9.4.1_450bps_hac.cfg'
# quality qscore filter for guppy. 0 means all reads are written to the output
basecalling_guppy_qscore_filter: 0
# command line flags directly passed to guppy
basecalling_guppy_flags: '-x cuda:0'

# UMI clustering and consensus
UMI_consensus: True
mismatches_allowed: 1       # number of mismatches that are allowed. NOT IMPLEMENTED YET
UMI_consensus_threshold: 2  # minimum required number of reads with a particular UMI. if set to <=1, all reads will be included


# alignment flags for samtools e.g. -F 2304 for RNA alignment
alignment_samtools_flags: ''
# command line flags for minimap2 DNA alignment
## alignment_minimap2_flags: '-ax map-ont -L'                                              # default options, optimized for alignment to genome
alignment_minimap2_flags: '-a -A2 -B4 -O12 -E4 --secondary=no --end-bonus=15'   # options good for targeted sequencing, minimizes gaps. Use --for-only flag to align to only the forward read of the reference sequence if all reads are already in the correct alignment.
# command line flags for graphmap2
alignment_graphmap2_flags: '-B 100'
# command line flags for ngmlr
alignment_ngmlr_flags: '-x ont --bam-fix'


# demux
demux: True
demux_threshold: 10  # count threshold for carrying through to subsequent rules. A demultiplexed file must contain at least this many sequences for further processing

# mutation analysis
mutation_analysis_quality_score_minimum: 5 # Minimum quality score needed for mutation to be counted. For amino acid level analysis, all nucleotides in the codon must be above the threshold for the mutation to be counted
sequence_length_threshold: 0.1              # Proportion of sequence length to be used as threshold for discarding sequences that are of abberant length. Ex. if set to 0.1 and length of trimmed reference sequence is 1000 bp, then all sequences either below 900 or above 1100 bp will not be analyzed
do_AA_analysis: True                        # If set to False, only nucleotide-level analysis will be generated. If set to true, AA-level analysis generated as well and, to prevent mismatch between nucleotide and amino acid -level analysis, sequences that do not pass AA-level quality checks will not be analyzed (e.g. sequences with frameshift mutations)
auto_detect_longest_ORF: False               # If set to true, automatically detects the longest ORF that can be identified in the reference sequence to use for protein level analysis. If analysis of a different protein sequence is desired, (e.g. shorter than full gene, so start or stop codon are not included) set to False and provide protein sequence as third reference in reference fasta file
highest_abundance_genotypes: 5                # number of most frequently appearing genotypes to find a representative sequence for and write the alignment (output of clean_alignment method) to a file. Sequence with the highest average quality score will be chosen. 

# mutation statistics
unique_genotypes_count_threshold: 5         # minimum number of reads of a particular genotype for that genotype to be included in unique genotypes count

# plot_mutation_distributions
percentile: 90                      # percentile of mutation distribution to show. X axis of plot will be 1.5x this percentile for the maximum of all distributions for the tag

# plot_mutations_aggregated
mutations_aggregated_Yaxis_absolute: False                 # display raw mutation counts on y axis. If set to False, y axis displays proportion of sequences with each mutation (total mutation / total sequences). If set to True, y axis displays total number of each mutation.

# plot_mut_spectrum
    # barcode group name to be used as the background for calculating the mutation spectrum
    #   to use, this barcode group name must be present within all samples being analyzed
# background: Y390-1000

# runs to be analyzed
runs:

    templateDilutions:
        # list of folder names that hold raw data in a reads folder ( data/{runname}/reads/ ). Basecalls from each of these will be combined in a directory for this tag ( sequences/batches/{tag}/{runname}/ ).
        runname:
            - 20210114_2207_MN35267_AFJ386_c4941675
            - 20210116_1641_MN35267_AFL239_42b6c1fa
        # fasta file that contains reference sequence in two forms: first is with barcode and UMI locations present, but marked by 'N's,
        #   second is trimmed such that each base is one for which analysis is desired. For amplicon sequencing, this likely means only bases that were PCR amplified,
        #   as bases that are present in primers are likely not informative and will slightly obscure evaluation of mutations/sequence, etc.
        #   Third sequence is optional, see `auto_detect_longest_ORF`
        reference: ref/testTrpB.fasta

        # required if UMI_consensus==True. regex patterns that used to identify UMIs. Specific to UMI tagging primers that are used. Both strands are queried and UMI that matches is appended to read name for use by `umi_tools group`. Even if only one UMI present, pattern should include the entire trimmed reference sequence.
        UMI_contexts:
            - NNNNTNNNNTNNNN
            - NNNNANNNNANNNNANNNN

        # # Sequence(s) to use for distinguishing forward and reverse orientations. For each, copy/paste subsequence from reference sequence that are present in forward and/or reverse primers and are distinct from the opposite orientation. Only necessary if consistent_orientation = False. Only one is necessary, but providing both forward and reverse will improve accuracy. Alignment of 10000 sequences for both forward and reverse sequences of length 8 takes ~7 seconds, and scales somewhat linear with sequence length, so be conservative if possible
        # orientation_alignment_sequence_f: GTATCGTG
        # orientation_alignment_sequence_r: CGATCACT

        # list barcode types to be used for demuxing. Demux'd files are named according to these barcodes in the order provided
        #   if (1) both sequence context and fasta files are provided, (2) context can be found within the reference sequence,
        #   and (3) the fasta file can be located

        barcodeInfo: # different types of barcodes present within each sequence, defined by the sequence context around the barcode location
            fwd: 
                context: CNNNNNNG          # copy and paste from reference fasta sequence. Include just enough sequence on one or both sides to distinguish from other barcodes, more than is necessary will result in more barcodes being ignored due to mismatches
                fasta: ref/barcodes_6_trimmed.fa
                reverseComplement: False    # set to True if corresponding barcodes in fasta file are defined as 5' to 3'. Default, False.
                hammingDistance: 1          # allowable hamming distance from true barcode. If any two of barcodes within provided fasta file are within this hamming distance from each other, demultiplexing will fail
            rvs:
                context: TNNNNNN  
                fasta: ref/barcodes_6_trimmed.fa
                reverseComplement: True
                hammingDistance: 1
            lineage:
                context: NNNNNNNNNNNNNNNN
                fasta: ref/barcodes_internal.fa
                reverseComplement: False
                hammingDistance: 3
                generate: 2                 # automatically generates a fasta file with this number of barcodes if the fasta file does not already exist. Uses the `generate_barcode_ref.py` script.

        barcodeGroups:  # names demultiplexed files according to given name instead of using name(s) of individual barcodes. groups must use the same pattern of barcode types.
                        #   For instance, if one group contains barcode designations for two barcodes types (e.g., fwd and rvs), then all other groups must contain barcode designations for those two barcode types
            Y390-1000:
                fwd: Barcode1
                rvs: Barcode2
            A1-1000:
                fwd: Barcode5
                rvs: Barcode2
            C1-1000:
                fwd: Barcode5
                rvs: Barcode6
            E1-1000:
                fwd: Barcode5
                rvs: Barcode10
            G1-1000:
                fwd: Barcode5
                rvs: Barcode14
            A1-100:
                fwd: Barcode9
                rvs: Barcode2
            C1-100:
                fwd: Barcode9
                rvs: Barcode6
            E1-100:
                fwd: Barcode9
                rvs: Barcode10
            G1-100:
                fwd: Barcode9
                rvs: Barcode14
            A1-10:
                fwd: Barcode13
                rvs: Barcode2
            C1-10:
                fwd: Barcode13
                rvs: Barcode6
            E1-10:
                fwd: Barcode13
                rvs: Barcode10
            G1-10:
                fwd: Barcode13
                rvs: Barcode14